name: $(BuildID)

trigger:
  batch: true
  branches:
    include:
      - develop

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'build'
    variables:
      CI: true
    jobs:
      - job: BuildMSDBack
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "16.x"
            displayName: "Install Node.js"

          - task: Npm@1
            inputs:
              command: "install"
            displayName: "Install dependencies"

          - template: test-and-coverage.yml

          - task: Npm@1
            inputs:
              command: "custom"
              customCommand: "run build"
            displayName: "Back build"

          - template: artifact-storage.yml
