# Jobs template for static website build
parameters:
  - name: env
    type: string
    default: dev

jobs:
  - job: msd_bo_site_build_install
    pool:
      name: "MSD Self hosted agents"
      demands:
        - environment -equals ${{ parameters.env }}
    displayName: Install node modules
    steps:
      - template: build/node.yml

      - template: build/install.yml

  - job: msd_bo_site_build_test
    # FIXME: libgles2 system package is missing from hosted agent
    #        temporarily disable self-hosted agent usage until support fixes
    #   pool:
    #     name: "MSD Self hosted agents"
    #     demands:
    #       - environment -equals ${{ parameters.env }}
    displayName: Run tests
    dependsOn: msd_bo_site_build_install
    steps:
      - template: build/node.yml

      - template: build/pre-tests.yml

      - template: build/e2e-tests.yml

  - job: msd_bo_site_build_package
    pool:
      name: "MSD Self hosted agents"
      demands:
        - environment -equals ${{ parameters.env }}
    dependsOn: msd_bo_site_build_install
    displayName: Build package
    steps:
      - template: build/node.yml

      - template: build/export.yml
        parameters:
          env: ${{ parameters.env }}

      - template: build/artifact.yml
