# Jobs template for static website release
parameters:
  - name: env
    type: string

  - name: instance
    type: string

jobs:
  - deployment: msd_bo_site_release_${{ parameters.env }}
    # FIXME: Docker is not installed on hosted agents
    #        Pool reclamation will be re-enabled when issue is fixed by IT
    #   pool:
    #     name: "MSD Self hosted agents"
    #     demands:
    #       - environment -equals ${{ parameters.env }}
    displayName: "[${{ upper(parameters.env) }}] Publish BO (${{ parameters.instance }})"
    environment: msd-${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: none

            - task: DownloadPipelineArtifact@2
              displayName: Get latest Artifact from CI pipeline
              inputs:
                buildType: "current"
                path: $(System.DefaultWorkingDirectory)/
                artifact: BO Static WebApp Export $(Build.BuildId)

            - task: AzureStaticWebApp@0
              displayName: Update BO Static WebApp in Azure Cloud
              inputs:
                output_location: "out"
                skip_app_build: true
                verbose: true
                is_static_export: true
                ${{ if not(eq(parameters.instance, 'production')) }}:
                  deployment_environment: ${{ parameters.instance }}
              env:
                azure_static_web_apps_api_token: $(bo-deployment-token)
