# Jobs template for static website release
parameters:
  - name: env
    type: string

  - name: tag
    type: string

  - name: instance
    type: string

jobs:
  - deployment: msd_bo_site_release_${{ parameters.env }}
    # FIXME: Docker is not installed on hosted agents
    #        Pool reclamation will be re-enabled when issue is fixed by IT
    #   pool:
    #     name: "MSD Self hosted agents"
    #     demands:
    #       - environment -equals ${{ parameters.env }}
    displayName: "[${{ upper(parameters.env) }}] Publish BO (${{ parameters.instance }})"
    environment: msd-${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: none

            - task: DownloadPipelineArtifact@2
              displayName: Get latest Artifact from CI pipeline
              inputs:
                buildType: "current"
                path: $(System.DefaultWorkingDirectory)/
                artifact: BO Static WebApp Export $(Build.BuildId)

            - task: AzureWebAppContainer@1
              displayName: Update Container in Azure WebApps
              inputs:
                azureSubscription: msd-${{ parameters.env }}-spn
                appName: app-msd-${{ parameters.env }}-bowebsite
                imageName: crmsd${{ parameters.env }}.azurecr.io/msd-bowebsite:${{ parameters.tag }}
                ${{ if and(eq(parameters.instance, 'smile'), eq(parameters.env, 'rec'))}}:
                  deployToSlotOrASE: true
                  resourceGroupName: rg-msd-${{ parameters.env }}
                  slotName: ${{ parameters.instance }}
